### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by bjvrielink** [ffquintella/puppet-tcpwrappers#1]
The module does not accept the following resource:
  tcpwrappers::allow { 'ALL6':
    service => 'ALL',
    address => '[2001:DEAD:BEEF::]/48',
  }

Please consider replacing the validate_re with something like:
Variant[Enum['ALL','LOCAL','UNKNOWN','KNOWN','PARANOID'],Stdlib::Host]
This also because the various validate_ functions are declared as deprecated by Stdlib.

**Comment by ffquintella** [comment]
Can you please submit a pull request with the requested changes? I will be glad to merge

**Comment by bjvrielink** [comment]
Will do. But, the solution I suggested requires a newer stdlib module than the 4.0.0 that is specified in the metadata.json. Standard data types were introduced in stdlib 4.13.0 and improved in 5.0.0. 4.13.0 was released in 2016.
Should I just add a new regex for IPv6 in allow.pp and deny.pp, or bump the minimum stdlib version and use their data types?

**Comment by bjvrielink** [comment]
See #2 for the regexp approach.

**Comment by ffquintella** [comment]
I merged the regex approach. It's simpler then changing the requirements.
